name: wafelzwaardutils
version: '1.0-SNAPSHOT'
main: me.verschillend.wafelzwaardutils.Wafelzwaardutils
api-version: '1.21'
description: Verschillends wafelzwaard utils plugin
author: Verschillend

permissions:
  wafelzwaard.bw:
    description: Allows bedwars command
    default: true
  wafelzwaard.cc:
    description: Allows chatcolor gui
    default: true
  wafelzwaard.spawn:
    description: Allows using spawn command
    default: true
  wafelzwaard.spawn.others:
    description: Allows teleporting other players to spawn
    default: op
  wafelzwaardutils.suffix:
    description: Allows using the suffix command and GUI
    default: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false