name: wafelzwaardutils
version: '1.0-SNAPSHOT'
main: me.verschillend.wafelzwaardutils.Wafelzwaardutils
api-version: '1.21'
description: Verschillends wafelzwaard utils plugin
author: Verschillend

permissions:
  wafelzwaard.bw:
    description: Allows bedwars command
    default: true
  wafelzwaard.cc:
    description: Allows chatcolor gui
    default: true
  wafelzwaard.spawn:
    description: Allows using spawn command
    default: true
  wafelzwaard.spawn.others:
    description: Allows teleporting other players to spawn
    default: op
  wafelzwaardutils.suffix:
    description: Allows using the suffix command and GUI
    default: true
  wafelzwaardutils.reload:
    description: Allows reloading the plugin configuration
    default: op
  wafelzwaardutils.oneblock.kick:
    description: Allows kicking players from your island
    default: true
  wafelzwaardutils.oneblock.invite:
    description: Allows inviting people to your island
    default: true
  wafelzwaardutils.discord:
    description: Allows /discord command
    default: true
  wafelzwaardutils.troll:
    description: Allows /troll command
    default: op
  wafelzwaardutils.gems:
    description: Allows checking own gems
    default: true
  wafelzwaardutils.gems.admin:
    description: Allows managing other players' gems
    default: op
  wafelzwaardutils.referral:
    description: Access to referral GUI
    default: true
  wafelzwaardutils.refer:
    description: Use referral codes
    default: true
  wafelzwaardutils.gemshop:
    description: Access to gem shop
    default: true
  wafelzwaardutils.blackjack:
    description: Play blackjack
    default: true
  wafelzwaardutils.dealer:
    description: Manage dealer gems
    default: op

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    SimpleVote:
      load: BEFORE
      required: false