name: wafelzwaardutils
version: '1.0-SNAPSHOT'
main: me.verschillend.wafelzwaardutils.Wafelzwaardutils
api-version: '1.21'
description: Verschillends wafelzwaard utils plugin
author: Verschillend

commands:
  bw:
    usage: /bw
  chatcolor:
    usage: /chatcolor

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false